### ISSUE TITLE
Small issues with the mouse over animation

### ISSUE THREAD

**Issue by Dinchy87** [BratchedDev/Bratched.Tools.RatingControl#4]
I have small issues with the mouse over animation that should fill up a rating (star) the control in my project is set up with this paraameters Height="40" ItemSpacing="10" IsEditable="True". The control itself is on a grid that has a width of 430 and i height of 200. so the rating control takes up the same width. The poblem is if you hover with the mouse ofer the First starts its ok but goiung further it does not follow the mous exactly. on mouse over 5 is fills up just 4 stars and on 4 only 3. The threshold should be fllowing the mouse exactly on the beggining of a star it should display the line there and not before. Can this be fixed somehow?!

Edit:

I have tested now the Code behind of this Control and the mouse tapps on 4 the controls says it a rating of 3. so something is not right.

Best regards.

**Comment by BratchedDev** [comment]
Yes! I have reproduced it. Now, I'm looking for. Thanks

**Comment by BratchedDev** [comment]
Corrected!
