### ISSUE TITLE
Color of the ratings

### ISSUE THREAD

**Issue by prinzemathew** [BratchedDev/Bratched.Tools.RatingControl#9]
Can we change the color of the ratings, I see the default is orange and yellow?

**Comment by BratchedDev** [comment]
(look at the readme file please)
You can use Foreground and Background Color to customize your ratings 

<rating:RatingControl ItemsCount="5" Value="1" >
	<rating:RatingControl.EmptyItemsDefinition>
		<rating:RateItemDefinition BackgroundColor="Red"/>
	</rating:RatingControl.EmptyItemsDefinition>
</rating:RatingControl>
